In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[2,3],[4,5]])
b = np.array([[0,1,2,3], [4,5,6,7]])
print(a)
print(b)

[[1 2]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
c = np.dot(a, b)
print(c)

[[ 8 11 14 17]
 [12 17 22 27]
 [20 29 38 47]]


In [11]:
max = c.max()
print(max)

47
